#pragma once

// NOTE:	This file is being generated by the CMake build process.
// 			Don't change this file by hand (except for testing during development)
//			Change YoaConfig.h.in instead please.

// version number set through CMake prejoect build process
#define YOA_VERSION_MAJOR 0
#define YOA_VERSION_MINOR 0
#define YOA_VERSION_PATCH 0

// toggle certain features of YoAudio
#define SDL2_FOUND true
#if SDL2_FOUND
#define FORCE_SDL 
#endif

#ifdef _DEBUG
#define SPDLOG_FOUND false
#if SPDLOG_FOUND
#define LOGGING_ENABLED true
#else
#define LOGGING_ENABLED false
#endif
#else
#define LOGGING_ENABLED false
#endif

#define AUDIO_THREAD_UPDATES false
// calls to YoManager::Update() per second
#define FRAME_RATE			60
// set to 0 for no limit on playing voices
#define MAX_VOICES 			0

// audio device configuration
#define TARGET_SAMPLERATE	48000
#define TARGET_CHANNELS		2
#define TARGET_BUFFER		4096
#define TARGET_BITDEPTH		16
