#ifndef _YOA_VERSION_H
#define _YOA_VERSION_H

// NOTE:	This file is being generated by the CMake build process.
// 			Don't change this file by hand (except for testing during development)
//			Change YoaConfig.h.in instead please.

// version number set through CMake prejoect build process
#define YOA_VERSION_MAJOR 0
#define YOA_VERSION_MINOR 0

// toggle certain features of YoAudio
#define SDL2_ENABLED true

#ifdef _DEBUG
#define LOGGING_ENABLED true
#else
#define LOGGING_ENABLED false
#endif


// calls to YoManager::Update() per second
#define FRAME_RATE 60;

// audio device configuration
#define AUDIO_FREQUENCY 48000
#define AUDIO_CHANNELS 2
#define AUDIO_SAMPLES 4096

#endif // _YOA_VERSION_H
