name: Matrix Build

on:
  workflow_dispatch:
  push:
    branches: [ "master", "develop", "feature/**", "editor", "linux", "msvc" ]
  pull_request:
    branches: [ "master", "develop", "feature/**", "editor" ]

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      build_timestamp: ${{steps.timestamp.outputs.timestamp}}
      build_id: v0.2.3_${{github.run_number}}_${{steps.timestamp.outputs.timestamp}}
    steps:
      - name: configure build id
        id: timestamp
        run: echo "timestamp=$(date -u +'%Y%m%d%H%M')" >> "$GITHUB_OUTPUT"

  build:
    needs: configure
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations.
      # Consider changing this to true when your workflow is stable.
      fail-fast: false
      
      matrix:
        os: [ ubuntu-latest ]
        c_compiler: [ clang, gcc ]
        build_type: [ Debug, Release ]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: windows-latest
            build_type: Release
            c_compiler: msvc
            cpp_compiler: cl.exe
          - os: windows-latest
            build_type: Debug
            c_compiler: msvc
            cpp_compiler: cl.exe

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: pull in git-submodules
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: git submodule update --init --recursive --remote
    
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      if: matrix.c_compiler == 'msvc'

    - name: Install Linux Dependencies
      shell: bash
      run: sudo apt install libsdl2-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build CMake output
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
    #- name: Test
      #working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration.
      # Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      #run: ctest --build-config ${{ matrix.build_type }}
    #- name: build documentation

    - uses: actions/upload-artifact@v4
      with:
        working-directory: ${{env.GITHUB_WORKSPACE}}
        name: ${{needs.configure.outputs.build_id}}-${{ matrix.os }}_${{ matrix.build_type }}_${{ matrix.c_compiler }}
        path: bin/*
        if: matrix.build_type == 'Release'
